### ISSUE TITLE
"Instruments" in the top left corner of sim don't work

### ISSUE THREAD

**Issue by davinderc** [udacity/fcnd-issue-reports#46] opened 2018-02-09 02:33 UTC
The altimeter and latitude and longitude readings in the top left corner of the simulator don't change at all when running in manual mode or even when running code directly. All values are 0.

**Comment by silentwater** [comment] 2018-02-12 18:49
Same problem as Waffle #10. Reason for problem already found and described in Waffle #10.

**Comment by domluna** [comment] 2018-02-15 17:28
duplicate of #10, closing

**Closed by domluna** 2018-02-15 17:28 UTC
Labels: bug, simulator, to do
